export const language = 
[
    "arabic",
    "bulgarian",
    "cebuano",
    "chinese",
    "czech",
    "english",
    "esperanto",
    "finnish",
    "greek",
    "japanese",
    "javanese",
    "latin",
    "mongolian",
    "rewrite",
    "serbian",
    "slovak",
    "speechless",
    "tagalog",
    "text-cleaned",
    "translated",
    "ukrainian"
]